[package]
name = "iana-media-types-codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector = "0.11.4"
anyhow = "1.0.66"
quote = "1.0.21"
syn = "1.0.103"
ureq = "2.5.0"
